site_name: Xmbtx
theme: 
  name: material
  icon:
    logo: material/library
  palette:
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
  language: zh

edit_uri: edit/main/docs

nav:
  - 主页:
#    - Home: index.md
    - 456: 123/456.md

extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
extra:
  homepage: http://xmbtx.github.io/xmbtx-blog/
  social: # icons
#   - icon: fontawesome/brands/bilibili
#     link: https://space.bilibili.com/
#     name: Bilibili | Xmbtx # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/Xmbtx
      name: GitHub | Xmbtx
## [bottom-left corner]
copyright: Copyright &copy; 2023-现在 凶猫不太凶 # 左下角的版权声明
