site_name: Xmbtx
theme: 
  name: material
  icon:
    logo: material/library
    admonition:
      abstract: fontawesome/brands/bilibili
  palette:
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
  language: zh

markdown_extensions: 
  - admonition # 折叠彩条图标插件
  - pymdownx.details # 折叠彩条图标插件
  - pymdownx.superfences # 折叠彩条图标插件
  - def_list # 任务列表
  - pymdownx.tasklist: # 任务列表
      custom_checkbox: true #  任务列表
#  - mdx_truly_sane_lists
  - abbr # 工具提示
  - attr_list # 工具提示
  - pymdownx.snippets # 工具提示
  - pymdownx.snippets: # 术语拓展
      auto_append: # 术语拓展
        - includes/abbreviations.md # 术语拓展
  - attr_list # 表情图标拓展
  - pymdownx.emoji: # 表情图标拓展
      emoji_index: !!python/name:material.extensions.emoji.twemoji # 表情图标拓展
      emoji_generator: !!python/name:material.extensions.emoji.to_svg # 表情图标拓展
  - pymdownx.critic # 格式Formatting
  - pymdownx.caret # 格式Formatting
  - pymdownx.keys # 格式Formatting
  - pymdownx.mark # 格式Formatting
  - pymdownx.tilde # 格式Formatting
      
edit_uri: edit/main/docs

nav:
  - 附录:
    - blog基础: blog/blog.md
    - 虚拟机c++学习记录: c/c.md
    - 小记: record/searching.md
    - 365: 365/365.md
  - 主页:
    - Home: index.md
    - 友链: friends.md
    - 直播间: live.md
  - Markdown:
    - Markdown学习记录: mkd/mkd.md
    - Markdownex: mkd/mkdex.md
  - OS:
    - Linux是怎样工作的: os/linux_work.md

extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - stylesheets/extra.css # 自定义折叠彩条图
extra:
  homepage: http://xmbtx.github.io/xmbtx-blog/
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://b23.tv/hc2nqdA
      name: Bilibili | Xmbtx # 鼠标悬浮提示
    - icon: fontawesome/brands/accessible-icon
      link: https://github.com/Xmbtx/xmbtx-blog/tree/master
      name: GitHub | Xmbtxの仓库
    - icon: fontawesome/brands/github
      link: https://github.com/Xmbtx
      name: GitHub | Xmbtx
## [bottom-left corner]
copyright: Copyright &copy; 2023-现在 凶猫不太凶 # 左下角的版权声明
